### ISSUE TITLE
Revisit alpine version locked at 3.13

### ISSUE THREAD

**Issue by rodrigoaguilera** [wodby/base-php#2]
Having an old alpine version limits what other apk packages can be installed inside the container, for example chromedriver that is at version 86 in alpine 3.13. 
It will be end of life in 6 months so better have some time to prepare.

Having a look at the issue linked that was introduced in this commit:
https://github.com/wodby/base-php/commit/64ca2ef594907e1b12bce62ce088b5de98b6b177
but it doesn't explain too much what breaks in wodby with newer versions of alpine. Is there tests for it?

I think is time to assume that the docker version installed will be high enough not to suffer from that issue.

What is the plan?

**Comment by csandanov** [comment]
that's the reason we have alpine 3.13 https://github.com/alpinelinux/docker-alpine/issues/182
the plan is to maintain both latest and 3.13 variants

**Comment by csandanov** [comment]
we're now build two variants: latest (3.15) and 3.13
